apiVersion: v1
data:
  pgbouncer.ini: W3BnYm91bmNlcl0KbGlzdGVuX2FkZHIgPSAqCmxpc3Rlbl9wb3J0ID0gNTQzMgp1bml4X3NvY2tldF9kaXIgPSAvdG1wCmF1dGhfZmlsZSA9IC9ldGMvcGdib3VuY2VyL3VzZXJsaXN0LnR4dAphdXRoX3R5cGUgPSBzY3JhbS1zaGEtMjU2CmFkbWluX3VzZXJzID0gcGdib3VuY2VyCjtwb29sX21vZGUgPSB0cmFuc2FjdGlvbgo7bWF4X2NsaWVudF9jb25uID0gNTAwMAo7bWF4X2RiX2Nvbm5lY3Rpb25zID0gNTAwCjtpZ25vcmVfc3RhcnR1cF9wYXJhbWV0ZXJzID0gZXh0cmFfZmxvYXRfZGlnaXRzCmxvZ2ZpbGUgPSAvdG1wL3BnYm91bmNlci5sb2cKCltkYXRhYmFzZXNdCmNlbGVyby1kYi1kZXZlbG9wID0gaG9zdD0xMC4yMjguNjUuMyBwb3J0PTU0MzIgZGJuYW1lPWNlbGVyby1kYi1kZXZlbG9wCg==
  userlist.txt: InBnYm91bmNlciIgIlNDUkFNLVNIQS0yNTYkNDA5Njo0cnlTTC9SeDJPTEhIbDlJcUNyNlE2M2lyWW00czdwQWd4b1J0bWQyckdNPSRJZjNQSzVObWZyUWpsMGNGcm5aT09yT1g1cjlnODlsZGY2MVNRWmduZXVJPTpvWWpHSzJFd1ZvbnIyNGFpZWFYOEwwaTRCOTZrWVk1cFVVNEgwYm0zSW5BPSIKImNlbGVyby1kYi1kZXZlbG9wIiAiU0NSQU0tU0hBLTI1NiQ0MDk2OmFFNzhCMEpYa0loT0NtYTVUaFVxM2VLbTNKZm5NY2Y1RzYvOHNRMWpOLzA9JDY4WWtzUkJBZytjOG9JbExyVGp4Zkp0K3Q3SG1TRVZVNjVDeHVKcUdnWmM9Om5aRXdqb2tMMUUwSjlyZm9takJhY0oyUTFlRktIdmFqV3dZZXhybzV5UFU9Igo=
kind: Secret
metadata:
  creationTimestamp: null
  name: pgbouncer-example-config
  namespace: pgbouncer
