apiVersion: v1
kind: Service
metadata:
  name: pgbouncer-example
  namespace: pgbouncer
  labels:
    app: pgbouncer-example
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: pgbouncer-example
